### ISSUE TITLE
Attempting Cargo Build

### ISSUE THREAD

**Issue by ezraek** [ff14wed/deucalion#20]
![image](https://github.com/ff14wed/deucalion/assets/136475906/18d35206-f205-4cf1-b607-ec06ee6b58d6)

Attempting to cargo build and it keeps failing, even after restarting.

**Comment by ff14wed** [comment]
The retour lib that's used for hooking requires a nightly install of rust (https://github.com/Hpmason/retour-rs#installation).
I haven't yet updated the version of the retour lib, but there shouldn't be any substantial differences with the latest version.

You'll have to use `rustup toolchain install nightly` to install rust. Hope that helps.

**Comment by ezraek** [comment]
Ran the command just to ensure my Rust was all right, but still hitting that same error captured above even after rebooting, unfortunately.

**Comment by ff14wed** [comment]
Did you make sure that the nightly version of Rust is your active toolchain?

**Comment by ezraek** [comment]
I... did not know that was a thing (newbie to Rust - just was following the post). Do you have the command offhand?

**Comment by ff14wed** [comment]
Apologies. I forgot about this issue for a while.

This doc should explain all you need to know about nightly: https://doc.rust-lang.org/book/appendix-07-nightly-rust.html

I'm closing this issue since this should resolve it.
